### ISSUE TITLE
Extract features from a batch of images

### ISSUE THREAD

**Issue by albertaparicio** [movienet/movienet-tools#4]
I am trying to extract Action features for a large dataset of videos. 

I have noticed that neither of the extractor sets, PersonDetector/ActionExtractor and ParallelPersonDetector/ParallelActionExtractor, support processing batches of images. From what I have been able to see, only a single image can be processed at a time.

I see that the parallel versions of the detector and extractor have a `batch_size` parameter, but is always set to 1.

I would like to know how could I take a batch of images, expressed in a NumPy array (shape [batch_size, height, width, channels]) or Torch tensor (shape [batch_size, channels, height, width]) and process it in a single call, without looping over the list of images to be processed.

Ideally I would like to construct a PyTorch Dataset class that gives me batches of images, that could come from any video and process them with the Detector and Extractor, so I can then use the extracted features in a custom classifier.

I hope this can be supported, since it would enable a much more efficient use of GPU processing. I think that being able to extract and predict with multiple GPUs is fine but only if each GPU is maxed out while doing so, and it looks like this is not the case with the current status of this project.

**Comment by ycxioooong** [comment]
For person_detector, ``imgs_per_gpu=1`` is fixed and cannot be extended to more images per GPU. Also, ActionExtractor(s) only support single sequence per GPU. So if you have ``N`` GPU, you are able to process ``N`` images/sequence at the same time.

We don't support multi images/sequences per GPU currently and we think it does not help improve the efficiency a lot since single image/sequence per GPU already make GPU-Util near 100%.

By the way, your demand is very similar to what we provide in ``scripts/extract_action_feats.py``. Instead of extracting action features per shot, you would like to extract action features per frame/sequence. So you could follow the code and replace the  ``action_extractor.src.dataset.ActionDataset`` to your own customized one.

**Comment by albertaparicio** [comment]
I see, thank you for your help and advice
