### ISSUE TITLE
Training the action model from scratch

### ISSUE THREAD

**Issue by albertaparicio** [movienet/movienet-tools#5]
I was looking into this project and I was wondering if there is a supported way for training the Action Recognition model from scratch. I have not seen any mention of it in the documentation nor I have seen any script that indicates this is supported.

Any pointers in this matter are appreciated. Thank you

**Comment by ycxioooong** [comment]
Hi there,

We do not support training and will not support it in the future.

But you could use [mmaction](https://github.com/open-mmlab/mmaction) for training action models.
Since our framework follows the same API design with [mmaction](https://github.com/open-mmlab/mmaction),
you could very easily transfer the pre-trained models from ``mmaction`` to ``movienet.tools`` and extract action features using ``movienet.tools``.

Besides, currently ``mmaction`` already supports a wide range of methods on all the action understanding tasks, including action recognition, action temporal detection, and spatial-temporal action detection.

**Comment by ycxioooong** [comment]
By the way, if you want to train person detection models yourself, please refer to [mmdetection](https://github.com/open-mmlab/mmdetection).
